
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'H_TOKEN O_TOKEN e : h_rule\n          | o_rule h_rule : H_TOKEN\n               | h_rule o_rule\n               | o_rule h_rule o_rule : O_TOKEN\n               | h_rule h_rule'
    
_lr_action_items = {'H_TOKEN':([0,2,3,4,5,6,7,8,9,10,],[4,4,4,-3,-6,4,4,4,4,4,]),'O_TOKEN':([0,2,3,4,5,6,7,8,9,10,],[5,5,5,-3,-6,5,5,5,5,5,]),'$end':([1,2,3,4,5,6,7,9,10,],[0,-1,-2,-3,-6,-7,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'e':([0,],[1,]),'h_rule':([0,2,3,6,7,8,9,10,],[2,6,9,10,9,9,6,6,]),'o_rule':([0,2,3,6,7,8,9,10,],[3,7,8,7,8,8,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> e","S'",1,None,None,None),
  ('e -> h_rule','e',1,'p_e','day19-parser.py',24),
  ('e -> o_rule','e',1,'p_e','day19-parser.py',25),
  ('h_rule -> H_TOKEN','h_rule',1,'p_h_rule','day19-parser.py',30),
  ('h_rule -> h_rule o_rule','h_rule',2,'p_h_rule','day19-parser.py',31),
  ('h_rule -> o_rule h_rule','h_rule',2,'p_h_rule','day19-parser.py',32),
  ('o_rule -> O_TOKEN','o_rule',1,'p_o_rule','day19-parser.py',37),
  ('o_rule -> h_rule h_rule','o_rule',2,'p_o_rule','day19-parser.py',38),
]
